version: '3.1'
services:
  trade-engine:
    build: ./
    ports:
      - 8080:8080
    environment:
      - SPRING_REDIS_HOST=redis
    depends_on:
      - redis
  redis:
    restart: always
    image: redis:7.0
    volumes:
      - ./data/redis-data:/data
    ports:
      - 6379:6379

